# -*- coding: utf-8 -*-
"""DataAnalytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19lk9KxtMW9yVH8gl1QbjD5pKh3ara7_l
"""

import pandas as pd
lst = ["Greek","For","Greek","i",'portal','for','Greek']
df=pd.DataFrame(lst)
print(df)

import pandas as pd
data = {'Name':['Tom','nick','Krish','jack'],
        'Age':[20,21,19,18]}
df=pd.DataFrame(data)
print(df)

import statistics
import numpy as np

numbers = [10, 20, 30, 40, 50, 20]

# Mean
mean_value = statistics.mean(numbers)

# Median
median_value = statistics.median(numbers)

# Mode
mode_value = statistics.mode(numbers)

# Variance
variance_value = statistics.variance(numbers)

# Standard Deviation
std_dev_value = statistics.stdev(numbers)

print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_dev_value)

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Sum and Mean
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Maximum and Minimum
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

# Reshape the array
reshaped_arr = arr.reshape(2, 3)
print("Reshaped Array:\n", reshaped_arr)

# Element-wise multiplication
arr2 = np.array([10, 20, 30, 40, 50, 60])
result = arr * arr2
print("Element-wise Multiplication:", result)

import numpy as np

# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
print("Addition:\n", A + B)

# Subtraction
print("Subtraction:\n", A - B)

# Matrix Multiplication
print("Matrix Multiplication:\n", np.dot(A, B))

# Transpose
print("Transpose of Matrix A:\n", A.T)

import numpy as np

# Generate random array of 10 numbers
random_arr = np.random.rand(10)

print("Random Array:", random_arr)

print("Mean:", np.mean(random_arr))
print("Standard Deviation:", np.std(random_arr))
print("Minimum:", np.min(random_arr))
print("Maximum:", np.max(random_arr))

from scipy import stats
import numpy as np

data = [10, 12, 9, 14, 13, 11, 10]

# Mean using scipy.stats
mean_value = stats.tmean(data)
print("Mean using scipy:", mean_value)

# One-sample t-test (test mean = 10)
t_stat, p_value = stats.ttest_1samp(data, 10)

print("T-statistic:", t_stat)
print("P-value:", p_value)

from scipy import integrate

# Function to integrate
def f(x):
    return x**2

result, error = integrate.quad(f, 0, 3)

print("Integration Result:", result)
print("Estimated Error:", error)

from scipy.optimize import minimize

# Function to minimize
def f(x):
    return x**2 + 5*x + 6

result = minimize(f, x0=0)

print("Minimum value:", result.fun)
print("Value of x at minimum:", result.x)

import numpy as np
import matplotlib.pyplot as plt

# Sample data
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

# Calculate slope (m) and intercept (b)
m, b = np.polyfit(x, y, 1)

print("Slope (m):", m)
print("Intercept (b):", b)

# Predicted values
y_pred = m * x + b

# Plot
plt.scatter(x, y)
plt.plot(x, y_pred)
plt.xlabel("X")
plt.ylabel("Y")
plt.title("Linear Regression using NumPy")
plt.show()

